### PR TITLE
Add priority value to SchedClassifier attach() call

### PR DESCRIPTION
**Pull request by anfredette**
Chages aya-template to work with API change introduced by pr #359

2nd part of change for issue #358

Signed-off-by: Andre Fredette <afredette@redhat.com>

### CODE REVIEW

**Comment by anfredette** [comment]
@alessandrod @dave-tucker I'm not sure this was the right way to fix the dependencies, but I believe this will make aya-template work with my tc priority pr and fix the build break.

**Comment by alessandrod** [comment]
Thank you! We need to hold off merging this until we do a new release of the aya crate, which we should probably do sometime next week

**Comment by anfredette** [comment]
When the new aya crate is released, I think we'll want to update this change to set the dependencies to crates.io instead of github.com/aya-rs/aya.

**Comment by anfredette** [comment]
Still waiting on the next version of Aya to be pushed to crates.io.

**Comment by anfredette** [comment]
The pr isn't required anymore due to changes in the API.

**Pull request closed without merging**
