### PR TITLE
Update README.md when using aya-template to run a sample XDP program

### LINKED ISSUE #17: Update README.md for running program by removing `--path` flag which does not exist in the generated program
Update README.md for xdp program by removing `--path` flag which does not exist in the generated program

Switch from 
```
sudo target/debug/{{project-name}} --path target/bpfel-unknown-none/debug/{{project-name}}
```

to 
```
sudo target/debug/{{project-name}} target/bpfel-unknown-none/debug/{{project-name}}
```

### PR DESCRIPTION
**Pull request by nitishm**
Closes #17 

@alessandrod @dave-tucker @willfindlay Since I havent tried any other template program (apart from XDP) I am not sure if this change would affect the other types.

Signed-off-by: Nitish Malhotra <nitish.malhotra@gmail.com>

### CODE REVIEW

**Review by willfindlay — CHANGES_REQUESTED** [review]
This doesn't seem correct. The XDP template still takes a --path argument, the path to the BPF object file. See the following usage example that I generated just now:
```
xdp-test 0.1.0

USAGE:
    xdp-test [OPTIONS] --path <path>

FLAGS:
    -h, --help       Prints help information
    -V, --version    Prints version information

OPTIONS:
    -i, --iface <iface>     [default: eth0]
    -p, --path <path>
```

What you might want to do is detect `{%-  if program_type == "xdp" -%}` and then conditionally add the extra --iface flag. But I can imagine this getting very complicated very quickly if we do the same thing with all program types.

**Comment by nitishm** [comment]
Ah the issue is in the docs in the sample program - https://github.com/aya-rs/book/blob/main/examples/myapp-02/myapp/src/main.rs#L18-L26. It uses positional args vs flags. I will fix that.

**Comment by nitishm** [comment]
@willfindlay with the XDP program I found that when getting the program object `bpf.program_mut()` it takes the program type and not the crate name (i.e. the project name)

Can you verify if this is the case of all program types?

**Comment by willfindlay** [comment]
> @willfindlay with the XDP program I found that when getting the program object `bpf.program_mut()` it takes the program type and not the crate name (i.e. the project name)
> 
> Can you verify if this is the case of all program types?

bpf.program_mut takes the program name, not the crate name or the program type. In the case of the XDP template, the program name should just happen to be the same as the crate name.

**Comment by nitishm** [comment]
> > @willfindlay with the XDP program I found that when getting the program object `bpf.program_mut()` it takes the program type and not the crate name (i.e. the project name)
> > Can you verify if this is the case of all program types?
> 
> bpf.program_mut takes the program name, not the crate name or the program type. In the case of the XDP template, the program name should just happen to be the same as the crate name.

I tried that with `myapp` being the name of the program but it errored out saying program `myapp` not found. When I switched it to `xdp` it worked

**Comment by willfindlay** [comment]
It's totally dependent on the name of your XDP program on the eBPF side. Are you sure you didn't just name your XDP program xdp?

**Comment by nitishm** [comment]
> It's totally dependent on the name of your XDP program on the eBPF side. Are you sure you didn't just name your XDP program xdp? 

Let me check. I am using the book so maybe that is the case. Just stepped away. Will take a look when I'm back

**Comment by nitishm** [comment]
> It's totally dependent on the name of your XDP program on the eBPF side. Are you sure you didn't just name your XDP program xdp? 

Let me check. I am using the book so maybe that is the case. Just stepped away. Will take a look when I'm back

**Comment by nitishm** [comment]
> > It's totally dependent on the name of your XDP program on the eBPF side. Are you sure you didn't just name your XDP program xdp?
> 
> Let me check. I am using the book so maybe that is the case. Just stepped away. Will take a look when I'm back

The book example was missing the name field from the program type macro. It was using `#[xdp]` instead of `#[xdp(name="{{ crate_name }})]` which I am guessing defaults to the program type name.

Closing this issue since nothing needs to change.

**Pull request closed without merging**
